var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/invite-team/route.js")
R.c("server/chunks/[root-of-the-server]__a912cd2e._.js")
R.c("server/chunks/node_modules_decdbaeb._.js")
R.c("server/chunks/_63876e62._.js")
R.c("server/chunks/_e93bbb28._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_027a6218._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_invite-team_route_actions_d9fb0e44.js")
R.m(31903)
module.exports=R.m(31903).exports
