var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/pos/send-link/route.js")
R.c("server/chunks/[root-of-the-server]__4b80f9ec._.js")
R.c("server/chunks/node_modules_decdbaeb._.js")
R.c("server/chunks/_63876e62._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/node_modules_resend_dist_index_mjs_0a305732._.js")
R.c("server/chunks/node_modules_027a6218._.js")
R.c("server/chunks/_next-internal_server_app_api_pos_send-link_route_actions_77ff99f5.js")
R.m(46724)
module.exports=R.m(46724).exports
