var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/invite-team/setup-link/route.js")
R.c("server/chunks/[root-of-the-server]__b7092a21._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_decdbaeb._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/_63876e62._.js")
R.c("server/chunks/ce889_server_app_api_admin_invite-team_setup-link_route_actions_24c1d5e1.js")
R.m(16008)
module.exports=R.m(16008).exports
