var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/orders/resend-confirmation/route.js")
R.c("server/chunks/[root-of-the-server]__a8034596._.js")
R.c("server/chunks/node_modules_decdbaeb._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/_63876e62._.js")
R.c("server/chunks/node_modules_027a6218._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/node_modules_resend_dist_index_mjs_0a305732._.js")
R.c("server/chunks/ce889_server_app_api_admin_orders_resend-confirmation_route_actions_499cd450.js")
R.m(45142)
module.exports=R.m(45142).exports
