var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/dispatch/route.js")
R.c("server/chunks/[root-of-the-server]__6f1d6749._.js")
R.c("server/chunks/node_modules_decdbaeb._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_e2a1a806.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/_63876e62._.js")
R.c("server/chunks/_next-internal_server_app_api_dispatch_route_actions_eda4d18f.js")
R.m(32675)
module.exports=R.m(32675).exports
