var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/cron/abandoned-cart/route.js")
R.c("server/chunks/[root-of-the-server]__38397c3c._.js")
R.c("server/chunks/_e93bbb28._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/node_modules_027a6218._.js")
R.c("server/chunks/_next-internal_server_app_api_cron_abandoned-cart_route_actions_d6fdf9f9.js")
R.m(60469)
module.exports=R.m(60469).exports
