var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/notify-back-in-stock/route.js")
R.c("server/chunks/[root-of-the-server]__1871a9c0._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_decdbaeb._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/_63876e62._.js")
R.c("server/chunks/_next-internal_server_app_api_notify-back-in-stock_route_actions_63c9ad3c.js")
R.m(681)
module.exports=R.m(681).exports
