var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/test-email/route.js")
R.c("server/chunks/[root-of-the-server]__97d20f17._.js")
R.c("server/chunks/node_modules_decdbaeb._.js")
R.c("server/chunks/_e93bbb28._.js")
R.c("server/chunks/_63876e62._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/node_modules_027a6218._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_test-email_route_actions_ff16a53f.js")
R.m(58215)
module.exports=R.m(58215).exports
