// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/account" | "/account/addresses" | "/account/orders" | "/account/orders/[id]" | "/account/profile" | "/admin" | "/admin/analytics" | "/admin/categories" | "/admin/customers" | "/admin/login" | "/admin/orders/[id]" | "/admin/products/new" | "/admin/settings" | "/catalog/auto-discounts" | "/catalog/categories" | "/catalog/discounts" | "/catalog/gift-cards" | "/catalog/products" | "/catalog/products/[id]/edit" | "/catalog/products/low-stock" | "/catalog/products/new" | "/checkout" | "/checkout/cancel" | "/checkout/direct" | "/checkout/success" | "/claim-account" | "/cms" | "/communications/emails" | "/contact" | "/craft" | "/customers" | "/customers/[id]" | "/customers/abandoned" | "/customers/forms" | "/customers/requests" | "/dresses" | "/faq" | "/finance" | "/finance/invoices" | "/finance/invoices/[id]" | "/finance/links" | "/gallery" | "/gift-card" | "/gift-cards" | "/gift-cards/success" | "/invite" | "/invoice/[id]" | "/login" | "/new-arrivals" | "/overview" | "/pay/[pos_id]" | "/policies/accessibility-statement" | "/policies/privacy-policy" | "/policies/refund-policy" | "/policies/shipping-policy" | "/policies/terms-and-conditions" | "/pos" | "/pos/history" | "/privacy" | "/products/[slug]" | "/register" | "/reset-password" | "/sale" | "/sales/analytics" | "/sales/orders" | "/sales/orders/[id]" | "/sales/payments" | "/sales/pre-orders" | "/sales/riders" | "/sales/riders/[id]" | "/sales/wholesalers" | "/search" | "/seo" | "/settings" | "/settings/assets" | "/settings/emails" | "/shipping" | "/shop" | "/size-guide" | "/team" | "/terms" | "/track" | "/whitelabel"
type AppRouteHandlerRoutes = "/api/abandoned/remind" | "/api/admin/contact-submissions/[id]" | "/api/admin/invite-team" | "/api/admin/invite-team/setup-link" | "/api/admin/orders/resend-confirmation" | "/api/admin/products" | "/api/admin/push/subscribe" | "/api/admin/set-wholesale" | "/api/admin/test-email" | "/api/admin/test-sms" | "/api/auth/forgot-password" | "/api/auth/logout" | "/api/checkout/auto-discount" | "/api/checkout/validate-code" | "/api/contact" | "/api/cron/abandoned-cart" | "/api/cron/abandoned-carts" | "/api/dispatch" | "/api/email/fulfillment" | "/api/gift-cards/issue" | "/api/gift-cards/purchase" | "/api/gift-cards/redeem" | "/api/gift-cards/resend" | "/api/gift-cards/validate" | "/api/invite" | "/api/invoice/paystack-link" | "/api/landing-route" | "/api/me" | "/api/newsletter/subscribe" | "/api/notify-back-in-stock" | "/api/paystack/initialize" | "/api/paystack/verify" | "/api/paystack/webhook" | "/api/pickup-ready" | "/api/pos/cancel" | "/api/pos/expire" | "/api/pos/send-link" | "/api/pos/session" | "/api/pos/session/[id]" | "/api/products" | "/api/verify-payment" | "/api/videos" | "/rss.xml"
type PageRoutes = never
type LayoutRoutes = "/" | "/account"
type RedirectRoutes = "/accessibility-statement" | "/category/[slug]" | "/new-arrivals" | "/product-page/[[...slug]]" | "/shop/new-arrivals" | "/shop/sale"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/accessibility-statement": {}
  "/account": {}
  "/account/addresses": {}
  "/account/orders": {}
  "/account/orders/[id]": { "id": string; }
  "/account/profile": {}
  "/admin": {}
  "/admin/analytics": {}
  "/admin/categories": {}
  "/admin/customers": {}
  "/admin/login": {}
  "/admin/orders/[id]": { "id": string; }
  "/admin/products/new": {}
  "/admin/settings": {}
  "/api/abandoned/remind": {}
  "/api/admin/contact-submissions/[id]": { "id": string; }
  "/api/admin/invite-team": {}
  "/api/admin/invite-team/setup-link": {}
  "/api/admin/orders/resend-confirmation": {}
  "/api/admin/products": {}
  "/api/admin/push/subscribe": {}
  "/api/admin/set-wholesale": {}
  "/api/admin/test-email": {}
  "/api/admin/test-sms": {}
  "/api/auth/forgot-password": {}
  "/api/auth/logout": {}
  "/api/checkout/auto-discount": {}
  "/api/checkout/validate-code": {}
  "/api/contact": {}
  "/api/cron/abandoned-cart": {}
  "/api/cron/abandoned-carts": {}
  "/api/dispatch": {}
  "/api/email/fulfillment": {}
  "/api/gift-cards/issue": {}
  "/api/gift-cards/purchase": {}
  "/api/gift-cards/redeem": {}
  "/api/gift-cards/resend": {}
  "/api/gift-cards/validate": {}
  "/api/invite": {}
  "/api/invoice/paystack-link": {}
  "/api/landing-route": {}
  "/api/me": {}
  "/api/newsletter/subscribe": {}
  "/api/notify-back-in-stock": {}
  "/api/paystack/initialize": {}
  "/api/paystack/verify": {}
  "/api/paystack/webhook": {}
  "/api/pickup-ready": {}
  "/api/pos/cancel": {}
  "/api/pos/expire": {}
  "/api/pos/send-link": {}
  "/api/pos/session": {}
  "/api/pos/session/[id]": { "id": string; }
  "/api/products": {}
  "/api/verify-payment": {}
  "/api/videos": {}
  "/catalog/auto-discounts": {}
  "/catalog/categories": {}
  "/catalog/discounts": {}
  "/catalog/gift-cards": {}
  "/catalog/products": {}
  "/catalog/products/[id]/edit": { "id": string; }
  "/catalog/products/low-stock": {}
  "/catalog/products/new": {}
  "/category/[slug]": { "slug": string; }
  "/checkout": {}
  "/checkout/cancel": {}
  "/checkout/direct": {}
  "/checkout/success": {}
  "/claim-account": {}
  "/cms": {}
  "/communications/emails": {}
  "/contact": {}
  "/craft": {}
  "/customers": {}
  "/customers/[id]": { "id": string; }
  "/customers/abandoned": {}
  "/customers/forms": {}
  "/customers/requests": {}
  "/dresses": {}
  "/faq": {}
  "/finance": {}
  "/finance/invoices": {}
  "/finance/invoices/[id]": { "id": string; }
  "/finance/links": {}
  "/gallery": {}
  "/gift-card": {}
  "/gift-cards": {}
  "/gift-cards/success": {}
  "/invite": {}
  "/invoice/[id]": { "id": string; }
  "/login": {}
  "/new-arrivals": {}
  "/overview": {}
  "/pay/[pos_id]": { "pos_id": string; }
  "/policies/accessibility-statement": {}
  "/policies/privacy-policy": {}
  "/policies/refund-policy": {}
  "/policies/shipping-policy": {}
  "/policies/terms-and-conditions": {}
  "/pos": {}
  "/pos/history": {}
  "/privacy": {}
  "/product-page/[[...slug]]": { "slug"?: string[]; }
  "/products/[slug]": { "slug": string; }
  "/register": {}
  "/reset-password": {}
  "/rss.xml": {}
  "/sale": {}
  "/sales/analytics": {}
  "/sales/orders": {}
  "/sales/orders/[id]": { "id": string; }
  "/sales/payments": {}
  "/sales/pre-orders": {}
  "/sales/riders": {}
  "/sales/riders/[id]": { "id": string; }
  "/sales/wholesalers": {}
  "/search": {}
  "/seo": {}
  "/settings": {}
  "/settings/assets": {}
  "/settings/emails": {}
  "/shipping": {}
  "/shop": {}
  "/shop/new-arrivals": {}
  "/shop/sale": {}
  "/size-guide": {}
  "/team": {}
  "/terms": {}
  "/track": {}
  "/whitelabel": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/account": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
