var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/push/subscribe/route.js")
R.c("server/chunks/[root-of-the-server]__e5d4bb5d._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_decdbaeb._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/_63876e62._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_push_subscribe_route_actions_26d7ff81.js")
R.m(62680)
module.exports=R.m(62680).exports
