var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_global-error/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__f62d412e._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_8a37abed._.js")
R.c("server/chunks/ssr/[root-of-the-server]__12211d46._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_@opentelemetry_api_index_d03d2993.js")
R.c("server/chunks/ssr/[root-of-the-server]__133a4282._.js")
R.c("server/chunks/ssr/node_modules_next_dist_25a30daf._.js")
R.c("server/chunks/ssr/node_modules_next_dist_22f8d72f._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/_next-internal_server_app__global-error_page_actions_75761787.js")
R.m(61837)
module.exports=R.m(61837).exports
