var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/contact-submissions/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__49f4aae2._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_decdbaeb._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/_63876e62._.js")
R.c("server/chunks/ce889_server_app_api_admin_contact-submissions_[id]_route_actions_2790b80e.js")
R.m(7635)
module.exports=R.m(7635).exports
