// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(dashboard)/catalog/auto-discounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/catalog/auto-discounts">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/catalog/auto-discounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/catalog/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/catalog/categories">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/catalog/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/catalog/discounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/catalog/discounts">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/catalog/discounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/catalog/gift-cards/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/catalog/gift-cards">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/catalog/gift-cards/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/catalog/products/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/catalog/products/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/catalog/products/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/catalog/products/low-stock/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/catalog/products/low-stock">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/catalog/products/low-stock/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/catalog/products/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/catalog/products/new">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/catalog/products/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/catalog/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/catalog/products">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/catalog/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/cms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cms">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/cms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/communications/emails/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/communications/emails">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/communications/emails/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/customers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/customers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/customers/abandoned/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers/abandoned">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/customers/abandoned/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/customers/forms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers/forms">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/customers/forms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/customers/requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers/requests">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/customers/requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/finance/invoices/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/invoices/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/finance/invoices/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/finance/invoices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/invoices">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/finance/invoices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/finance/links/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/links">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/finance/links/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/overview">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/pos/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pos/history">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/pos/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/pos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pos">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/pos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/sales/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/sales/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/sales/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/sales/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/sales/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/orders">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/sales/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/sales/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/payments">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/sales/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/sales/pre-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/pre-orders">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/sales/pre-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/sales/riders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/riders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/sales/riders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/sales/riders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/riders">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/sales/riders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/sales/wholesalers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/wholesalers">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/sales/wholesalers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/seo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seo">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/seo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/settings/assets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/assets">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/settings/assets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/settings/emails/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/emails">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/settings/emails/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/team">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/test-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-orders">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/test-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/account/addresses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/addresses">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/account/addresses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/account/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/account/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/account/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/orders">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/account/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/account/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/profile">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/account/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/checkout/cancel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout/cancel">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/checkout/cancel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/checkout/direct/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout/direct">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/checkout/direct/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/checkout/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout/success">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/checkout/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/claim-account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/claim-account">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/claim-account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/craft/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/craft">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/craft/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/dresses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dresses">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/dresses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/gallery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gallery">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/gallery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/gift-card/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gift-card">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/gift-card/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/gift-cards/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gift-cards">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/gift-cards/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/gift-cards/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gift-cards/success">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/gift-cards/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/new-arrivals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/new-arrivals">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/new-arrivals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/pay/[pos_id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pay/[pos_id]">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/pay/[pos_id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/policies/accessibility-statement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/policies/accessibility-statement">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/policies/accessibility-statement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/policies/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/policies/privacy-policy">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/policies/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/policies/refund-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/policies/refund-policy">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/policies/refund-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/policies/shipping-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/policies/shipping-policy">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/policies/shipping-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/policies/terms-and-conditions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/policies/terms-and-conditions">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/policies/terms-and-conditions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/products/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/products/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/sale/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sale">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/sale/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/shipping/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shipping">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/shipping/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/shop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/shop/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/size-guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/size-guide">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/size-guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/track/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/track">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/track/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/whitelabel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/whitelabel">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/whitelabel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/admin/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/categories">> = Specific
  const handler = {} as typeof import("../../src/app/admin/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/customers">> = Specific
  const handler = {} as typeof import("../../src/app/admin/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../src/app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/products/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products/new">> = Specific
  const handler = {} as typeof import("../../src/app/admin/products/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/invite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invite">> = Specific
  const handler = {} as typeof import("../../src/app/invite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/invoice/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/invoice/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/abandoned/remind/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/abandoned/remind">> = Specific
  const handler = {} as typeof import("../../src/app/api/abandoned/remind/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/contact-submissions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/contact-submissions/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/contact-submissions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/invite-team/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/invite-team">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/invite-team/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/invite-team/setup-link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/invite-team/setup-link">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/invite-team/setup-link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/orders/resend-confirmation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/orders/resend-confirmation">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/orders/resend-confirmation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/products">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/push/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/push/subscribe">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/push/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/revalidate-discounts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/revalidate-discounts">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/revalidate-discounts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/set-wholesale/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/set-wholesale">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/set-wholesale/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/test-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/test-email">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/test-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/test-sms/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/test-sms">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/test-sms/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/forgot-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/forgot-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/checkout/auto-discount/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout/auto-discount">> = Specific
  const handler = {} as typeof import("../../src/app/api/checkout/auto-discount/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/checkout/validate-code/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout/validate-code">> = Specific
  const handler = {} as typeof import("../../src/app/api/checkout/validate-code/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../src/app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/abandoned-cart/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/abandoned-cart">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/abandoned-cart/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/abandoned-carts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/abandoned-carts">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/abandoned-carts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/expire-reservations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/expire-reservations">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/expire-reservations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/sync-payment-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/sync-payment-status">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/sync-payment-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dispatch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dispatch">> = Specific
  const handler = {} as typeof import("../../src/app/api/dispatch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/email/fulfillment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email/fulfillment">> = Specific
  const handler = {} as typeof import("../../src/app/api/email/fulfillment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/gift-cards/issue/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gift-cards/issue">> = Specific
  const handler = {} as typeof import("../../src/app/api/gift-cards/issue/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/gift-cards/purchase/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gift-cards/purchase">> = Specific
  const handler = {} as typeof import("../../src/app/api/gift-cards/purchase/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/gift-cards/redeem/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gift-cards/redeem">> = Specific
  const handler = {} as typeof import("../../src/app/api/gift-cards/redeem/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/gift-cards/resend/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gift-cards/resend">> = Specific
  const handler = {} as typeof import("../../src/app/api/gift-cards/resend/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/gift-cards/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gift-cards/validate">> = Specific
  const handler = {} as typeof import("../../src/app/api/gift-cards/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inventory/check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/check">> = Specific
  const handler = {} as typeof import("../../src/app/api/inventory/check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/invite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invite">> = Specific
  const handler = {} as typeof import("../../src/app/api/invite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/invoice/paystack-link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invoice/paystack-link">> = Specific
  const handler = {} as typeof import("../../src/app/api/invoice/paystack-link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/landing-route/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/landing-route">> = Specific
  const handler = {} as typeof import("../../src/app/api/landing-route/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/newsletter/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/newsletter/subscribe">> = Specific
  const handler = {} as typeof import("../../src/app/api/newsletter/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notify-back-in-stock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notify-back-in-stock">> = Specific
  const handler = {} as typeof import("../../src/app/api/notify-back-in-stock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/paystack/initialize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/paystack/initialize">> = Specific
  const handler = {} as typeof import("../../src/app/api/paystack/initialize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/paystack/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/paystack/verify">> = Specific
  const handler = {} as typeof import("../../src/app/api/paystack/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/paystack/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/paystack/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/paystack/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pickup-ready/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pickup-ready">> = Specific
  const handler = {} as typeof import("../../src/app/api/pickup-ready/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pos/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pos/cancel">> = Specific
  const handler = {} as typeof import("../../src/app/api/pos/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pos/expire/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pos/expire">> = Specific
  const handler = {} as typeof import("../../src/app/api/pos/expire/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pos/send-link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pos/send-link">> = Specific
  const handler = {} as typeof import("../../src/app/api/pos/send-link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pos/session/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pos/session/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/pos/session/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pos/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pos/session">> = Specific
  const handler = {} as typeof import("../../src/app/api/pos/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products">> = Specific
  const handler = {} as typeof import("../../src/app/api/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/videos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/videos">> = Specific
  const handler = {} as typeof import("../../src/app/api/videos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/rss.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/rss.xml">> = Specific
  const handler = {} as typeof import("../../src/app/rss.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/account/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/account">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/account/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
