var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/newsletter/subscribe/route.js")
R.c("server/chunks/[root-of-the-server]__fcd36506._.js")
R.c("server/chunks/_e93bbb28._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/node_modules_027a6218._.js")
R.c("server/chunks/_next-internal_server_app_api_newsletter_subscribe_route_actions_d0bc5698.js")
R.m(62134)
module.exports=R.m(62134).exports
