var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/gift-cards/redeem/route.js")
R.c("server/chunks/[root-of-the-server]__b2bc916e._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_decdbaeb._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/_63876e62._.js")
R.c("server/chunks/_next-internal_server_app_api_gift-cards_redeem_route_actions_7528edf9.js")
R.m(31076)
module.exports=R.m(31076).exports
