var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/cron/abandoned-carts/route.js")
R.c("server/chunks/[root-of-the-server]__92f46a53._.js")
R.c("server/chunks/_e93bbb28._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/node_modules_027a6218._.js")
R.c("server/chunks/_next-internal_server_app_api_cron_abandoned-carts_route_actions_c505bcfa.js")
R.m(45114)
module.exports=R.m(45114).exports
