var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/me/route.js")
R.c("server/chunks/[root-of-the-server]__0bc92dd8._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_decdbaeb._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/_63876e62._.js")
R.c("server/chunks/_next-internal_server_app_api_me_route_actions_3ee82308.js")
R.m(23033)
module.exports=R.m(23033).exports
